import glob
import os
Import('inc_dir')
Import('build_dir')
Import('src_dir')
env = Environment(CPPPATH = ["../" + inc_dir], LIBS = [])
execute = env.Program("test_db", ["jsondb.cpp", "test.cpp", "helpers.cpp", "log.cpp", "sha256.cpp", "pass.cpp"])
execute = env.Program("test_app", glob.glob("../src/*.cpp"))

